
 
CREATE DATABASE estudiante_1;
GO


CREATE TABLE  SALA(
COD_SALA INT NOT NULL PRIMARY KEY,
NOMBRE VARCHAR (100) NOT NULL,
CAPACIDAD INT NOT NULL,
EDIFICIO VARCHAR (100) NOT NULL
)

CREATE TABLE DOCENTE(
    USER_DOC INT NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR (100) NOT NULL,
    PROFESION VARCHAR (100) NOT NULL,
    RUT VARCHAR (12) NOT NULL,
    EMAIL VARCHAR (50) DEFAULT ('sinCorreo@mail.com'),
    TELEFONO VARCHAR (20) DEFAULT ('sinTelefono')
)

CREATE TABLE ESTUDIANTE (
    NRO_MATRICULA INT NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR (100) NOT NULL,
    FECHA_NAC DATE NOT NULL,
    ANO_INGRESO INT NOT NULL,
    RUT VARCHAR (12) NOT NULL,
    DIRECCION VARCHAR (100) NOT NULL,
    TELEFONO VARCHAR (20) DEFAULT ('sinTelefono'),
    EMAIL VARCHAR (50) DEFAULT ('sinCorreo@mail.com')
)

CREATE TABLE MODULO (
    COD_MOD VARCHAR (20) NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR (100) NOT NULL,
    CANTIDAD_HORAS INT NOT NULL,
    EXIMIBLE VARCHAR (5) NOT NULL
)

CREATE TABLE IMPARTE (
    COD_SALA_IMPARTE INT NOT NULL,
    COD_MODULO_IMPARTE VARCHAR (20) NOT NULL,
    DIA VARCHAR (10) NOT NULL,
    HORA VARCHAR (10) NOT NULL,
    CONSTRAINT idSala FOREIGN KEY (COD_SALA_IMPARTE) REFERENCES SALA(COD_SALA),
    CONSTRAINT idModulo FOREIGN KEY (COD_MODULO_IMPARTE) REFERENCES MODULO(COD_MOD) 
)

CREATE TABLE DICTA (    
    JORNADA VARCHAR (50) NOT NULL,
    USER_DOC_DICTA INT NOT NULL,
    COD_MODULO_DICTA VARCHAR (20) NOT NULL, 
    CONSTRAINT userDoctDicta FOREIGN KEY (USER_DOC_DICTA) REFERENCES DOCENTE(USER_DOC),
    CONSTRAINT codModuloImparte FOREIGN KEY (COD_MODULO_DICTA) REFERENCES MODULO(COD_MOD) 
)


CREATE TABLE CURSA (
    NRO_MATRICULA_CURSA INT NOT NULL,
    COD_MOD_CURSA VARCHAR (20) NOT NULL,
    ASISTENCIA INT NOT NULL,
    NOTA_FINAL DECIMAL (2,1) NOT NULL,
    OPORTUNIDAD INT NOT NULL,
    ESTADO VARCHAR (20) NOT NULL,
    SEMESTRE VARCHAR (20) NOT NULL,
    CONSTRAINT nroMatriculaCursa FOREIGN KEY (NRO_MATRICULA_CURSA) REFERENCES ESTUDIANTE(NRO_MATRICULA),
    CONSTRAINT codModuloCursa FOREIGN KEY (COD_MOD_CURSA) REFERENCES MODULO(COD_MOD) 
)

