

CREATE PROCEDURE firstProcedure @nro_matricula INT, @semestre VARCHAR (20)
AS
SELECT est.NOMBRE,
       cur.SEMESTRE, mod.NOMBRE AS
       NOMBRE_MODULO,
       imp.HORA,
       sal.NOMBRE AS NOMBRE_SALA,
       doc.NOMBRE AS NOMBRE_DOCENTE
FROM ESTUDIANTE AS est 
LEFT JOIN CURSA cur ON est.NRO_MATRICULA = cur.NRO_MATRICULA_CURSA
LEFT JOIN MODULO mod ON cur.COD_MOD_CURSA = mod.COD_MOD
LEFT JOIN IMPARTE imp ON mod.COD_MOD = imp.COD_MODULO_IMPARTE
LEFT JOIN SALA sal ON imp.COD_SALA_IMPARTE = sal.COD_SALA
LEFT JOIN DICTA dic ON dic.COD_MODULO_DICTA = mod.COD_MOD
LEFT JOIN DOCENTE doc ON dic.USER_DOC_DICTA = doc.USER_DOC
WHERE est.NRO_MATRICULA = @nro_matricula AND cur.SEMESTRE = @semestre
GO
EXEC firstProcedure @nro_matricula = 1, @semestre = 'primero';


/*
second exercise
*/
CREATE FUNCTION COUNTMODULOS 
(@nro_matricula INT)
RETURNS INT
AS
BEGIN
    DECLARE @quantity INT    
    SELECT @quantity = COUNT(mod.COD_MOD) 
    FROM MODULO mod
    LEFT JOIN CURSA cur ON mod.COD_MOD = cur.COD_MOD_CURSA
    LEFT JOIN ESTUDIANTE est ON cur.NRO_MATRICULA_CURSA = est.NRO_MATRICULA
    WHERE cur.ESTADO = 'aprobado' AND est.NRO_MATRICULA = 2
    RETURN @quantity
END
GO

SELECT dbo.COUNTMODULOS(1)
/*
end second exercise
*/


/*
THIRD EXERCISE
*/
CREATE FUNCTION AVERAGE_STUDENT_ 
(@nro_matricula INT)
RETURNS INT
AS
BEGIN
    DECLARE @average DECIMAL (2,1)   
    SELECT @average = AVG(cur.NOTA_FINAL)
    FROM ESTUDIANTE AS est
    LEFT JOIN CURSA cur ON est.NRO_MATRICULA = cur.NRO_MATRICULA_CURSA
    WHERE est.NRO_MATRICULA = 1
    RETURN @average
END
GO

SELECT dbo.AVERAGE_STUDENT_(1)
/*
END THIRD EXERCISE
*/